name: Check Installer

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install-linux:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge+MSS
        run: |
          sudo rm -rf $(which mamba)
          cd $GITHUB_WORKSPACE
          chmod +x LinuxMac.sh
          sudo ./LinuxMac.sh -a
      - name: Test MSS installed
        run: |
          . /home/runner/mambaforge/bin/activate mssenv
          msui --version | grep "Mission Support System (MSS)"
    
  install-macos:
    runs-on: macos-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge+MSS
        run: |
          sudo rm -rf $(which mamba)
          cd $GITHUB_WORKSPACE
          chmod +x LinuxMac.sh
          sudo ./LinuxMac.sh -a
      - name: Test MSS installed
        run: |
          . /Users/runner/mambaforge/bin/activate mssenv
          msui --version | grep "Mission Support System (MSS)"
          
          
  install-windows:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge+MSS (1/2) (needs new shell to recognise mamba)
        run: |
          cd %GITHUB_WORKSPACE%
          Windows.bat -a
      - name: Install mambaforge+MSS (2/2)
        run: |
          cd %GITHUB_WORKSPACE%
          set PATH=%PATH%;%USERPROFILE%\mambaforge\mambabin
          Windows.bat -a
      - name: Test MSS installed
        run: |
          set PATH=%PATH%;%USERPROFILE%\mambaforge\mambabin
          call mamba.bat activate mssenv
          msui --version | findstr /i /c:"Mission Support System (MSS)"
