name: Check Installer

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install-linux:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge+MSS
        run: |
          sudo rm -rf $(which mamba)
          cd $GITHUB_WORKSPACE
          chmod +x LinuxMac.sh
          sudo ./LinuxMac.sh -a
      - name: Test MSS installed
        run: |
          sudo /root/mambaforge/envs/mssenv/bin/msui --version | grep "Mission Support System (MSS)"
    
  install-macos:
    runs-on: macos-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge+MSS
        run: |
          sudo rm -rf $(which mamba)
          cd $GITHUB_WORKSPACE
          chmod +x LinuxMac.sh
          sudo ./LinuxMac.sh -a
      - name: Test MSS installed
        run: |
          sudo /Users/runner/mambaforge/envs/mssenv/bin/msui --version | grep "Mission Support System (MSS)"
          
  install-windows:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge (1/2)
        run: |
          cd %GITHUB_WORKSPACE%
          curl -L0  https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe --output mambaforge-installer.exe
          call mambaforge-installer.exe -Wait -ArgumentList "/S /RegisterPython=1 /AddToPath=1"
      - name: Install mambaforge+MSS (2/2)
        run: |
          cd %GITHUB_WORKSPACE%
          set PATH=%PATH%;%USERPROFILE%\mambaforge\mambabin
          Windows.bat -a
      - name: Test MSS installed
        run: |
          set PATH=%PATH%;%USERPROFILE%\mambaforge\mambabin
          call mamba.bat activate mssenv
          msui --version | findstr /i /c:"Mission Support System (MSS)"
