name: Check Installer (scheduled)

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1'

jobs:
  install-mss-on-linux-from-scratch:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install miniforge+MSS
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x LinuxMac.sh
          ./LinuxMac.sh -a
      - name: Test MSS installed by direct call
        run: |
          /home/runner/Miniforge/envs/mssenv/bin/msui --version | grep "Mission Support System (MSS)"
      - name: Test MSS installed in activated env
        run: |
          . /home/runner/Miniforge/etc/profile.d/conda.sh
          . /home/runner/Miniforge/etc/profile.d/mamba.sh
          mamba init
          mamba activate mssenv
          msui --version | grep "Mission Support System (MSS)"
          

  install-mss-on-existing-linux-miniforge-installation:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - name: Install miniforge by curl(1/3)
        run: |
          curl -L0 "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh" --output miniforge.sh
          chmod +x miniforge.sh
          script -q -c "./miniforge.sh -u -b -p ~/Miniforge"
          eval "$(/home/runner/Miniforge/bin/conda shell.bash hook)"
          mamba init
      - name: check mamba info(2/3)
        run: |
          eval "$(/home/runner/Miniforge/bin/conda shell.bash hook)"
          mamba info
      - name: Install MSS by LinuxMac.sh -a (3/3)
        run: |
          eval "$(/home/runner/Miniforge/bin/conda shell.bash hook)"
          cd $GITHUB_WORKSPACE
          chmod +x LinuxMac.sh
          ./LinuxMac.sh -a
      - name: Test MSS installed
        run: |
          /home/runner/Miniforge/envs/mssenv/bin/msui --version | grep "Mission Support System (MSS)"
          
    
  install-mss-on-macos-from-scratch:
    runs-on: macos-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Install miniforge+MSS
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x LinuxMac.sh
          ./LinuxMac.sh -a
      - name: Test MSS installed
        run: |
          /Users/runner/Miniforge/envs/mssenv/bin/msui --version | grep "Mission Support System (MSS)"

  install-mss-on-existing-macos-miniforge-installation:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Install miniforge by curl(1/3)
        run: |
          curl -L0 "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh" --output miniforge.sh
          chmod +x miniforge.sh
          script -q output.txt ./miniforge.sh -u -b -p ~/Miniforge
          eval "$(/Users/runner/Miniforge/bin/conda shell.bash hook)"
          mamba init
      - name: check mamba info(2/3)
        run: |
          eval "$(/Users/runner/Miniforge/bin/conda shell.bash hook)"
          mamba info
      - name: Install MSS by LinuxMac.sh -a (3/3)
        run: |
          eval "$(/Users/runner/Miniforge/bin/conda shell.bash hook)"
          cd $GITHUB_WORKSPACE
          chmod +x LinuxMac.sh
          ./LinuxMac.sh -a
      - name: Test MSS installed
        run: |
          /Users/runner/Miniforge/envs/mssenv/bin/msui --version | grep "Mission Support System (MSS)"

  install-mss-on-windows-from-scratch:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v3

      - name: Install miniforge+MSS (1/2) (needs new shell to recognise mamba)
        run: |
          cd %GITHUB_WORKSPACE%
          Windows.bat -a
      - name: Install miniforge+MSS (2/2)
        run: |
          cd %GITHUB_WORKSPACE%
          set PATH=%PATH%;%USERPROFILE%\Miniforge\condabin
          Windows.bat -a
      - name: Test MSS installed
        run: |
          set PATH=%PATH%;%USERPROFILE%\Miniforge\condabin
          call conda.bat activate mssenv
          msui --version | findstr /i /c:"Mission Support System (MSS)"
          

  install-mamba-on-windows-pwsh:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v3

      - name: Install miniforge by curl(1/2)
        run: |
          curl.exe -fsSLo miniforge.exe https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe
          Start-Process .\miniforge.exe -Wait -ArgumentList "/InstallationType=JustMe /RegisterPython=1 /AddToPath=1 /S /D=$($env:USERPROFILE)\Miniforge"

      - name: check mamba info(2/2)
        run: |
          $env:Path += ";$($env:USERPROFILE)\Miniforge\condabin"
          mamba info

  install-mss-on-existing-windows-miniforge-installation:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4

      - name: Install miniforge by curl(1/3)
        run: |
          curl.exe -fsSLo miniforge.exe https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe
          start /wait "" miniforge.exe /InstallationType=JustMe /RegisterPython=1 /AddToPath=1 /S /D=%USERPROFILE%\Miniforge
      - name: check mamba info(2/3)
        run: |
          set PATH=%PATH%;%USERPROFILE%\Miniforge\condabin
          mamba info
      - name: Install MSS by Windows.bat -a (3/3)
        run: |
          set PATH=%PATH%;%USERPROFILE%\Miniforge\condabin
          Windows.bat -a
      - name: Test MSS installed
        run: |
          set PATH=%PATH%;%USERPROFILE%\Miniforge\condabin
          call conda.bat activate mssenv
          msui --version | findstr /i /c:"Mission Support System (MSS)"

          
          
